Repository rick1e/shout-subgroup, pull requests merged in 2024-08, with the labels that each got.

#33 Remove Subgroups
  src/shout_subgroup/delete_subgroup.py
  src/shout_subgroup/main.py
  src/shout_subgroup/repository.py
  tests/test_delete_subgroup.py
Labels: enhancement

#41 Users can mention themselves when creating and modifying groups
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/utils.py
  tests/test_utils.py
Labels: enhancement

#42 Refactor repo functions
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/repository.py
  tests/test_group_chat_listener.py
Labels: refactor

#43 Can create subgroups containing users without usernames
  src/shout_subgroup/database.py
  src/shout_subgroup/models.py
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/repository.py
  src/shout_subgroup/utils.py
  tests/test_create_subgroup.py
  tests/test_utils.py
Labels: enhancement

#45 Handle modification of subgroups when a user does not have a username
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/repository.py
  src/shout_subgroup/utils.py
  tests/test_modify_subgroup.py
  tests/test_utils.py
Labels: enhancement

#46 Add and Remove users from Group Chat
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/main.py
  src/shout_subgroup/repository.py
  src/shout_subgroup/shout.py
  tests/test_group_chat_listener.py
Labels: enhancement

#47 Can remove users from subgroups if they don't have a username
  src/shout_subgroup/main.py
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/utils.py
  tests/test_remove_subgroup_members.py
Labels: enhancement

#48 Containerize the application
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  requirements.lock
  src/shout_subgroup/__init__.py
Labels: infrastructure

#50 Refactor kick members code
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/main.py
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/remove_subgroup_members.py
  src/shout_subgroup/repository.py
  tests/test_group_chat_listener.py
  tests/test_remove_subgroup_members.py
Labels: refactor

#55 Fixed bug plus minor linting
  src/shout_subgroup/shout.py
Labels: bug

#51 Issue 35
  .env-template
  docker-compose.yml
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/shout_subgroup/database.py
  src/shout_subgroup/delete_subgroup.py
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/list_subgroup.py
  src/shout_subgroup/main.py
  src/shout_subgroup/models.py
  src/shout_subgroup/modify_subgroup.py
  src/shout_subgroup/remove_subgroup_members.py
  src/shout_subgroup/repository.py
  src/shout_subgroup/shout.py
Labels: infrastructure

#59 Add users to group chat based on telegram id
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/repository.py
  tests/test_group_chat_listener.py
Labels: enhancement

#61 Removing users from group chat when a user does not have a username
  src/shout_subgroup/group_chat_listener.py
  src/shout_subgroup/repository.py
  tests/test_group_chat_listener.py
  tests/test_utils.py
Labels: refactor
